version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 84000
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 84000
      POSTGRES_DB: intilaq_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    image: omaahassanin/intilaq-ai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
      - postgres

volumes:
  mongodb_data:
  redis_data:
  postgres_data: