# ======================== BUILDER STAGE ==========================
FROM intilaq/base:latest AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends wget \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
    && tar -xvzf dockerize-linux-amd64-v0.6.1.tar.gz -C /usr/local/bin \
    && rm dockerize-linux-amd64-v0.6.1.tar.gz

COPY requirements.fastapi.txt .
RUN pip install --no-cache-dir -r requirements.fastapi.txt

# ======================== FINAL STAGE ==========================
FROM intilaq/base:latest

WORKDIR /app
ENV PYTHONPATH="/app"

# نسخ الحزم والأدوات من builder
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY . /app
COPY ./templates /app/templates
COPY certs/cert.pem /app/cert.pem
COPY certs/key.pem /app/key.pem
COPY alembic.ini /app/alembic.ini
COPY migrations /app/alembic

EXPOSE 8000
EXPOSE 5692

CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5692", "-m", "uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000",  "--ssl-keyfile", "/app/certs/key.pem", "--ssl-certfile", "/app/certs/cert.pem"]