FROM python:3.11-slim

WORKDIR /app

ENV PYTHONPATH=/app

COPY requirements.notification.txt .
RUN pip install --no-cache-dir --no-build-isolation -r requirements.notification.txt

COPY . .
COPY ./templates /app/templates
CMD ["python", "main.py"]
