"""Add/update fields in Education model

Revision ID: 248f3535ae1a
Revises: 43690c6f5a17
Create Date: 2025-01-24 18:41:26.109783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248f3535ae1a'
down_revision: Union[str, None] = '43690c6f5a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
