"""Add/update fields in Education model

Revision ID: 3259ae43f826
Revises: 
Create Date: 2025-01-24 16:31:34.696450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3259ae43f826'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('header_id', sa.Integer(), nullable=False))
    op.drop_constraint('education_user_id_fkey', 'education', type_='foreignkey')
    op.create_foreign_key(None, 'education', 'header', ['header_id'], ['id'])
    op.drop_column('education', 'user_id')
    op.add_column('logs', sa.Column('header_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'logs', 'header', ['header_id'], ['id'])
    op.drop_column('logs', 'personal_info_id')
    op.alter_column('reset_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reset_codes', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('logs', sa.Column('personal_info_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_column('logs', 'header_id')
    op.add_column('education', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'education', type_='foreignkey')
    op.create_foreign_key('education_user_id_fkey', 'education', 'header', ['user_id'], ['id'])
    op.drop_column('education', 'header_id')
    # ### end Alembic commands ###
