"""sync models with code changes

Revision ID: 55ae1d776938
Revises: 
Create Date: 2026-02-19 14:31:54.299690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55ae1d776938'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE SCHEMA IF NOT EXISTS hr_auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS outbox")
    op.execute("CREATE SCHEMA IF NOT EXISTS cv")
    op.execute("CREATE SCHEMA IF NOT EXISTS cv_auth")

    op.create_table('reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cv_auth'
    )
    op.create_index(op.f('ix_cv_auth_reset_codes_id'), 'reset_codes', ['id'], unique=False, schema='cv_auth')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cv_auth'
    )
    op.create_index(op.f('ix_cv_auth_users_email'), 'users', ['email'], unique=True, schema='cv_auth')
    op.create_index(op.f('ix_cv_auth_users_id'), 'users', ['id'], unique=False, schema='cv_auth')
    op.create_index(op.f('ix_cv_auth_users_username'), 'users', ['username'], unique=True, schema='cv_auth')
    op.create_table('hr_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hr_auth'
    )
    op.create_index(op.f('ix_hr_auth_hr_reset_codes_id'), 'hr_reset_codes', ['id'], unique=False, schema='hr_auth')
    op.create_table('hr_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('company_field', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_email'),
    schema='hr_auth'
    )
    op.create_table('events_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'FAILED', name='outbox_status_enum', schema='outbox'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    schema='outbox'
    )
    op.create_index('ix_outbox_scheduler', 'events_outbox', ['status', 'scheduled_at'], unique=False, schema='outbox')
    op.create_table('processed_events',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('consumer_name', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key', 'consumer_name', name='pk_processed_events'),
    schema='outbox'
    )
    op.create_table('header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('github_profile', sa.String(length=255), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cv_auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='cv'
    )
    op.create_table('awards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('award', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['cv.header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('certification_title', sa.String(length=255), nullable=True),
    sa.Column('upload', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['cv.header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('degree_and_major', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['cv.header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['cv.header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('objective',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['cv.header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['cv.header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('skills_languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['cv.header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    op.create_table('volunteering_experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['cv.header.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cv'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteering_experience', schema='cv')
    op.drop_table('skills_languages', schema='cv')
    op.drop_table('projects', schema='cv')
    op.drop_table('objective', schema='cv')
    op.drop_table('experience', schema='cv')
    op.drop_table('education', schema='cv')
    op.drop_table('certifications', schema='cv')
    op.drop_table('awards', schema='cv')
    op.drop_table('header', schema='cv')
    op.drop_table('processed_events', schema='outbox')
    op.drop_index('ix_outbox_scheduler', table_name='events_outbox', schema='outbox')
    op.drop_table('events_outbox', schema='outbox')
    op.drop_table('hr_users', schema='hr_auth')
    op.drop_index(op.f('ix_hr_auth_hr_reset_codes_id'), table_name='hr_reset_codes', schema='hr_auth')
    op.drop_table('hr_reset_codes', schema='hr_auth')
    op.drop_index(op.f('ix_cv_auth_users_username'), table_name='users', schema='cv_auth')
    op.drop_index(op.f('ix_cv_auth_users_id'), table_name='users', schema='cv_auth')
    op.drop_index(op.f('ix_cv_auth_users_email'), table_name='users', schema='cv_auth')
    op.drop_table('users', schema='cv_auth')
    op.drop_index(op.f('ix_cv_auth_reset_codes_id'), table_name='reset_codes', schema='cv_auth')
    op.drop_table('reset_codes', schema='cv_auth')
    # ### end Alembic commands ###
