"""Add/update fields in Education model

Revision ID: 7368fcd03f94
Revises: 3259ae43f826
Create Date: 2025-01-24 17:07:36.560100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7368fcd03f94'
down_revision: Union[str, None] = '3259ae43f826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('header_id', sa.Integer(), nullable=True))
    op.drop_constraint('awards_user_id_fkey', 'awards', type_='foreignkey')
    op.create_foreign_key(None, 'awards', 'header', ['header_id'], ['id'])
    op.drop_column('awards', 'user_id')
    op.add_column('certifications', sa.Column('header_id', sa.Integer(), nullable=True))
    op.drop_constraint('certifications_user_id_fkey', 'certifications', type_='foreignkey')
    op.create_foreign_key(None, 'certifications', 'header', ['header_id'], ['id'])
    op.drop_column('certifications', 'user_id')
    op.add_column('experience', sa.Column('header_id', sa.Integer(), nullable=True))
    op.drop_constraint('experience_user_id_fkey', 'experience', type_='foreignkey')
    op.create_foreign_key(None, 'experience', 'header', ['header_id'], ['id'])
    op.drop_column('experience', 'user_id')
    op.add_column('objective', sa.Column('header_id', sa.Integer(), nullable=True))
    op.drop_constraint('objective_user_id_fkey', 'objective', type_='foreignkey')
    op.create_foreign_key(None, 'objective', 'header', ['header_id'], ['id'])
    op.drop_column('objective', 'user_id')
    op.add_column('projects', sa.Column('header_id', sa.Integer(), nullable=True))
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'header', ['header_id'], ['id'])
    op.drop_column('projects', 'user_id')
    op.add_column('skills_languages', sa.Column('header_id', sa.Integer(), nullable=False))
    op.drop_constraint('skills_languages_user_id_fkey', 'skills_languages', type_='foreignkey')
    op.create_foreign_key(None, 'skills_languages', 'header', ['header_id'], ['id'])
    op.drop_column('skills_languages', 'user_id')
    op.add_column('volunteering_experience', sa.Column('header_id', sa.Integer(), nullable=True))
    op.drop_constraint('volunteering_experience_user_id_fkey', 'volunteering_experience', type_='foreignkey')
    op.create_foreign_key(None, 'volunteering_experience', 'header', ['header_id'], ['id'])
    op.drop_column('volunteering_experience', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteering_experience', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'volunteering_experience', type_='foreignkey')
    op.create_foreign_key('volunteering_experience_user_id_fkey', 'volunteering_experience', 'header', ['user_id'], ['id'])
    op.drop_column('volunteering_experience', 'header_id')
    op.add_column('skills_languages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'skills_languages', type_='foreignkey')
    op.create_foreign_key('skills_languages_user_id_fkey', 'skills_languages', 'header', ['user_id'], ['id'])
    op.drop_column('skills_languages', 'header_id')
    op.add_column('projects', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'header', ['user_id'], ['id'])
    op.drop_column('projects', 'header_id')
    op.add_column('objective', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'objective', type_='foreignkey')
    op.create_foreign_key('objective_user_id_fkey', 'objective', 'header', ['user_id'], ['id'])
    op.drop_column('objective', 'header_id')
    op.add_column('experience', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.create_foreign_key('experience_user_id_fkey', 'experience', 'header', ['user_id'], ['id'])
    op.drop_column('experience', 'header_id')
    op.add_column('certifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.create_foreign_key('certifications_user_id_fkey', 'certifications', 'header', ['user_id'], ['id'])
    op.drop_column('certifications', 'header_id')
    op.add_column('awards', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'awards', type_='foreignkey')
    op.create_foreign_key('awards_user_id_fkey', 'awards', 'header', ['user_id'], ['id'])
    op.drop_column('awards', 'header_id')
    # ### end Alembic commands ###
