"""Add HR tables

Revision ID: c40fe20f9b5f
Revises: 28e27ecaaeb6
Create Date: 2025-05-03 11:56:58.527245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40fe20f9b5f'
down_revision: Union[str, None] = '28e27ecaaeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hr_section'
    )
    op.create_index(op.f('ix_hr_section_hr_reset_codes_id'), 'hr_reset_codes', ['id'], unique=False, schema='hr_section')
    op.create_table('hr_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('company_field', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_email'),
    schema='hr_section'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_users', schema='hr_section')
    op.drop_index(op.f('ix_hr_section_hr_reset_codes_id'), table_name='hr_reset_codes', schema='hr_section')
    op.drop_table('hr_reset_codes', schema='hr_section')
    # ### end Alembic commands ###
