"""Add/update Add link field to certifications and make upload optional

Revision ID: fab225fe4a94
Revises: c47fc12bd0ad
Create Date: 2025-01-31 11:08:29.137547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab225fe4a94'
down_revision: Union[str, None] = 'c47fc12bd0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certifications', sa.Column('link', sa.Text(), nullable=True))
    op.alter_column('skills_languages', 'skills',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills_languages', 'skills',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('certifications', 'link')
    # ### end Alembic commands ###
